services:
  client:
    container_name: powerbidz-client
    build:
      context: ./client
      dockerfile: DockerFile
    image: powerbidz-client
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./client/.env


  server:
    container_name: powerbidz-server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: powerbidz-server
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
      - recommendation-service
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://powerbidz:powerbidzpassword@db:5432/powerbidz_db
      - RECOMMENDER_URL=http://recommendation-service:5000
    env_file:
      - ./server/.env

  recommendation-service:
    container_name: powerbidz-recommendation-service
    build:
      context: ./recommendation_service
      dockerfile: Dockerfile
    image: powerbidz-recommendation-service
    working_dir: /app
    ports:
      - "5050:5000"
    volumes:
      - ./recommendation_service:/app

  db:
    image: postgres:16
    container_name: powerbidz-db
    restart: always
    environment:  
      POSTGRES_USER: powerbidz
      POSTGRES_PASSWORD: powerbidzpassword
      POSTGRES_DB: powerbidz_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
